# CREATE MEME
# POST http://localhost:3000/memes
# { url : ""}
POST http://localhost:3000/memes
content-type : application/json

{
    "url": "https://www.instagram.com/reel/CV-DtiZAuhs/",
    "platform": "instagram",
    "contentType": "post",
    "preview": "https://picsum.photos/id/202/200/300",
    "storeURL": "https://picsum.photos/id/203/200/300",
    "title": "A spoof of Raja Babu"
} 
###
#Create MEME BY SENDING URL and TITLE
POST http://localhost:3000/memes/bookmark
content-type : application/json

{
    "url": "https://www.instagram.com/reel/CV-DtiZAuhs/",
    "title": "asdf asdf asdf asdf asdf"
} 
###

# GET http://localhost:3000/memes?page=0
GET http://localhost:3000/memes?page=3
###
# GET http://localhost:3000/memes/user/:userId?page=0
GET http://localhost:3000/memes/user/0e178286-41e7-4c60-bb9f-759ee3de5f1c

###
# GET http://localhost:3000/memes/collection/:collectionId?page=0
GET http://localhost:3000/memes/collection/0dddd2c6-4bc2-4b40-845b-f5027395c130
###

# GET http://localhost:3000/annotation-form/collection/:collectionId
GET http://localhost:3000/annotation-form/collection/30bf4e8d-6e66-48fb-8327-805b413d1ef6
###

# GET http://localhost:3000/annotations/collection/:collectionId/meme/:memeId
GET http://localhost:3000/annotations/collection/30bf4e8d-6e66-48fb-8327-805b413d1ef6/meme/0b3845a4-5c8c-4cd1-987e-763e342f0140

###

# CREATE A NEW ANNOTATION
# POST http://localhost:3000/annotations
# { url : ""}
POST http://localhost:3000/annotations/collection/30bf4e8d-6e66-48fb-8327-805b413d1ef6/meme/16b8bc58-d846-45c6-9e55-500dd386fe0d
content-type : application/json

{
    "annotations" : [
        {
            "key" : "hateful",
            "value" : "0",
            "type" : "radio"
        },
        {
            "key" : "cringe",
            "value" : "0",
            "type" : "radio"
        },
        {
            "key" : "funny",
            "value" : "1",
            "type" : "radio"
        }
    ]
} 
###